Update circleci config

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,7 +11,7 @@ jobs:
       - image: circleci/ruby:2.4.1-node-browsers
       - image: circleci/postgres:10-alpine-ram
         environment:
-          POSTGRES_USER: root
+          POSTGRES_USER: postgres
           POSTGRES_DB:  database_validations_test
       - image: circleci/mysql:5.7
         environment:
@@ -53,15 +53,19 @@ jobs:
           command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
 
       - run:
-          name: Waiting for PostgreSQL to start
-          command: |
-            for i in `seq 1 10`;
-            do
-              nc -z localhost 5432 && echo Success && exit 0
-              echo -n .
-              sleep 2
-            done
-            echo Failed waiting for Postgres && exit 1
+          name: Wait for Postgresql Server
+          command: dockerize -wait tcp://localhost:5432 -timeout 1m
+
+      # - run:
+      #     name: Waiting for PostgreSQL to start
+      #     command: |
+      #       for i in `seq 1 10`;
+      #       do
+      #         nc -z localhost 5432 && echo Success && exit 0
+      #         echo -n .
+      #         sleep 2
+      #       done
+      #       echo Failed waiting for Postgres && exit 1
 
       - save_cache:
           paths:
